env:
  global:
    - PKG_VER="1.1.8"
    - NAME="linux-kernel-utilities"
    - DESC="Utilities to compile & update linux kernels for Debian and deriv's (e.g. Ubuntu, LinuxMint, etc.)"
    - URL="https://github.com/mtompkins/linux-kernel-utilities"
    - A_INST="hooks/fpm-after-install.sh"
    - B_REMOVE="hooks/fpm-before-uninstall.sh"
    - MAINT="nobody@outlook.com"
    - ARCH="all"
sudo: required
dist: xenial
before_install:
  #- rvm install 2.7.0
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - sudo add-apt-repository -y ppa:duggan/bats
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:beineri/opt-qt562-xenial
  - sudo apt -y update
  - sudo apt -y install bats gcc make fakeroot libncurses5 libncurses5-dev kernel-package build-essential pkg-config libnotify-bin gnupg qt56tools qt56svg qt56script
  - sudo apt -y install ruby-dev
   #- sudo gem install bundler
  #- sudo bundle update
  # - sudo gem install ffi
  - sudo gem install --no-document fpm
script: 
  - bats ./unitTesting/tests-linux-kernel-utilities.bats
  - source /opt/qt56/bin/qt56-env.sh
  - fpm -s dir -t deb -n "${NAME}" -v "${PKG_VER}" -a "${ARCH}" --deb-no-default-config-files --after-install "${A_INST}" --before-remove "${B_REMOVE}" -m "${MAINT}" --description "${DESC}" --url "${URL}" ../linux-kernel-utilities=/opt

addons:
  code_climate:
    repo_token: af81e68f1d0e98adef124a52b75c13fff35e8da804b9276e3086e1a837685541
deploy:
  provider: releases
  api_key:
    secure: gWR2v4CMDRE1SomBwINCDTWqr8TrXCyB6jamPe5bxQIkEjbzcW3uTiHXs3eXWo2bf+zEILWO6PyEcAMcUIZrQi3Bib2SmcqaM6MnDZFxeBie4QDiALbiQYycHFT3Md+08Ka6xcG9DdftXhn9kPFmbumhKUx8YqMrCxyiBheR5liYzSSSJyEq7o54Oxs6hH3mcnfhYHk3PY4aIxcX2sKAfk7OpKwPni4JOsgl+AHXzcsT8nsNMhFfdnBz9cgfm7CWXq8TjyPIAY7YseRBM7uLAAejLOYb4BJzir8z9Wt7ctVlMJaxH+Po4eXzlOYIVxKYSp3gibUeD+3G2+TjwsEevYPdsIpIZFUvIc66VDyLMMb0wkPbIuzOCvCpOc1srFWDxpPOJLk5UOEDrdLdd3pSaRUDL20RimffuV+GjosrHDy2bPrEhOzdHhBYnFqWutWOTwi6/oLfRvrk829LANlO92SWCJyteQIvqieNp223Lel1zv4AL2O54DXW5U062fKB7d82OFX48kN4CYKre/jIYhui9lMXWyBa6YPWYDFUZ8dAwFj6+q/ycS4XChj588QmL2x2ltAchzmB/0ubW+UQOKS7Q5yKDpWqb/ALeDCgN5kxzJ1N9WWRgmw3VYeQv3WhxDEvp+CCtWHAerBT2kdP31jhq6hoJ72FXHpDntnjkww=
  file: linux-kernel-utilities_${PKG_VER}_${ARCH}.deb
  skip_cleanup: true
  on:
    repo: mtompkins/linux-kernel-utilities
    tags: true

